#Override Values for Apigee Environment |Hybrid 1.10.3 on GKE Cluster deployed with ArgoCD and Helm

gcp:
  region: us-west1
  projectID: hybrid-terraform-471100

k8sCluster:
  name: argocd-test
  region: us-west1 # Must be the closest Google Cloud region to your cluster.
org: hybrid-terraform-471100
orgscopedUDCA: true
instanceID: "argo1"

imagePullSecrets:
  - name: gcr-cred

nodeSelector:
 # This flag determines if the scheduling passes/fails if the labels are missing.
 requiredForScheduling: false
 apigeeRuntime:
   key: "cloud.google.com/gke-nodepool"
   value: "apigee-runtime"
 apigeeData:
   key: "cloud.google.com/gke-nodepool"
   value: "apigee-data"

hub: gcr.io/apigee-release/hybrid
envs:
- name: argo-env
  serviceAccountSecretRefs:
    synchronizer: "apigee-sa"
    udca: "apigee-sa"
    runtime: "apigee-sa"


synchronizer:
  replicaCountMin: '1'
  replicaCountMax: '2'
 
runtime:
  replicaCountMin: '1'
  replicaCountMax: '2'

udca:
  serviceAccountRef: "apigee-sa"
  hostNetwork: false

