{{- template "helmVersionCheck" . }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: apigee-ingressgateway
  namespace: {{ include "namespace" . }}
  labels:
    apigee.cloud.google.com/platform: apigee
