apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apigee

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "apigee-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: apigee-

vars:
- fieldref:
    fieldPath: spec.conversion.webhook.clientConfig.service.namespace
  name: CERTIFICATE_NAMESPACE
  objref:
    apiVersion: v1
    group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: apigeedeployments.apigee.cloud.google.com


resources:
- ../crd
