# Default values for apigee-redis.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

contractProvider: https://apigee.googleapis.com
namespace: apigee
apigeeGroupID: 998
apigeeUserID: 999
nodeSelector:
  requiredForScheduling: true
  apigeeRuntime:
    key: "cloud.google.com/gke-nodepool"
    value: "apigee-runtime"
  apigeeData:
    key: "cloud.google.com/gke-nodepool"
    value: "apigee-data"
imagePullSecrets: []
tolerations: []
affinity: {}
# Apigee Redis
redis:
  auth:
    password: "iloveapis123"
    secretProviderClass: ""
  image:
    url: "gcr.io/apigee-release/hybrid/apigee-redis"
    tag: "1.15.1"
    pullPolicy: IfNotPresent
  replicaCount: 2
  terminationGracePeriodSeconds: 600
  resources:
    requests:
      cpu: 500m
  readinessProbe:
    initialDelaySeconds: 0
    periodSeconds: 5
    timeoutSeconds: 3
    successThreshold: 1
    failureThreshold: 12
  livenessProbe:
    initialDelaySeconds: 0
    periodSeconds: 5
    timeoutSeconds: 3
    successThreshold: 1
    failureThreshold: 6
  envoy:
    image:
      url: "gcr.io/apigee-release/hybrid/apigee-envoy"
      tag: "1.15.1"
      pullPolicy: IfNotPresent
    replicaCountMin: 1
    replicaCountMax: 1
    targetCPUUtilizationPercentage: 75
    terminationGracePeriodSeconds: 600
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 2000m
        memory: 2Gi
    readinessProbe:
      periodSeconds: 5
      timeoutSeconds: 3
      failureThreshold: 12
    livenessProbe:
      periodSeconds: 5
      timeoutSeconds: 3
      failureThreshold: 6
# Apigee Guardrails
guardrails:
  image:
    url: "gcr.io/apigee-release/hybrid/apigee-watcher"
    tag: "1.15.1"
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 500m
      memory: 64Mi
