# Default values for apigee-telemetry.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

contractProvider: https://apigee.googleapis.com
org: ""
k8sCluster:
  name: ""
  region: ""
gcp:
  region: us-central1
  projectID: ""
  projectIDRuntime: ""
  workloadIdentity:
    enabled: false
  federatedWorkloadIdentity:
    enabled: false
    tokenExpiration: 3600
namespace: apigee
apigeeGroupID: 998
apigeeUserID: 999
nodeSelector:
  requiredForScheduling: true
  apigeeRuntime:
    key: "cloud.google.com/gke-nodepool"
    value: "apigee-runtime"
  apigeeData:
    key: "cloud.google.com/gke-nodepool"
    value: "apigee-data"
serviceAccountSecretProviderClass: ""
# Hybrid container logger.
logger:
  enabled: false
  terminationGracePeriodSeconds: 30
  image:
    url: "gcr.io/apigee-release/hybrid/apigee-fluent-bit"
    tag: "1.15.1"
    pullPolicy: IfNotPresent
  serviceAccountPath:
  livenessProbe:
    failureThreshold: 3
    initialDelaySeconds: 0
    periodSeconds: 60
    successThreshold: 1
    timeoutSeconds: 1
  resources:
    limits:
      cpu: 200m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 250Mi
  nodeSelector:
    key: "apigee.cloud.google.com/apigee-logger-enabled"
    value: "true"
  storageMaxChunks: 128
  bufferChunkSize: 256k
  bufferMaxSize: "104857600"
  bufferMemoryLimit: 150MB
  flushInterval: 1
  workers: 1
  proxyURL:
# Apigee Metrics Autoscaling
customAutoscaling:
  enabled: true
# Apigee Metrics.
metrics:
  enabled: true
  disablePrometheusPipeline: true
  terminationGracePeriodSeconds: 300
  serviceAccountPath:
  aggregator:
    resources:
      limits:
        cpu: 500m
        memory: 3Gi
      requests:
        cpu: 500m
        memory: 512Mi
  appStackdriverExporter:
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 128m
        memory: 512Mi
  collector:
    image:
      url: "gcr.io/apigee-release/hybrid/apigee-open-telemetry-collector"
      tag: "1.15.1"
      pullPolicy: IfNotPresent
    usePromVarSyntaxV2: true
    resources:
      limits:
        cpu: 500m
        memory: 2Gi
      requests:
        cpu: 2m
        memory: 512Mi
    readinessProbe:
      httpGet:
        path: /health/status
        port: 9092
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      successThreshold: 1
      failureThreshold: 3
    livenessProbe:
      httpGet:
        path: /health/status
        port: 9092
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      successThreshold: 1
      failureThreshold: 5
  proxyStackdriverExporter:
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 128m
        memory: 512Mi
  adapter:
    image:
      url: "gcr.io/apigee-release/hybrid/apigee-prometheus-adapter"
      tag: "1.15.1"
      pullPolicy: IfNotPresent
    serviceAccountPath:
    containerPort: 6443
    readinessProbe:
      httpGet:
        path: /healthz
        port: 6443
        scheme: HTTPS
      periodSeconds: 5
      timeoutSeconds: 3
      failureThreshold: 10
    livenessProbe:
      httpGet:
        path: /healthz
        port: 6443
        scheme: HTTPS
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 5
    resources:
      limits:
        cpu: 500m
        memory: 4Gi
      requests:
        cpu: 100m
        memory: 128Mi
  prometheus:
    image:
      url: "gcr.io/apigee-release/hybrid/apigee-prom-prometheus"
      tag: "1.15.1"
      pullPolicy: IfNotPresent
    args:
      storage_tsdb_retention: 48h
    containerPort: 9090
    readinessProbe:
      httpGet:
        path: /-/ready
        port: 9090
      periodSeconds: 5
      timeoutSeconds: 3
      failureThreshold: 120
    livenessProbe:
      httpGet:
        path: /-/healthy
        port: 9090
      periodSeconds: 5
      timeoutSeconds: 3
      failureThreshold: 6
    resources:
      limits:
        cpu: 500m
        memory: 4Gi
      requests:
        cpu: 128m
        memory: 512Mi
  sdSidecar:
    image:
      url: "gcr.io/apigee-release/hybrid/apigee-stackdriver-prometheus-sidecar"
      tag: "1.15.1"
      pullPolicy: IfNotPresent
    containerPort: 9091
    stackdriverApiAddress: "https://monitoring.googleapis.com:443/"
  proxyURL:
# Lets always use the tag so its easy to debug know which change helm is been validated
# Apigee Guardrails
guardrails:
  image:
    url: "gcr.io/apigee-release/hybrid/apigee-watcher"
    tag: "1.15.1"
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 500m
      memory: 64Mi
